# Generated by Django 2.1.5 on 2019-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190110_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Confirmado?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, verbose_name='É da equipe?'),
        ),
    ]
