CREATE DATABASE AGENDAMENTO;

USE AGENDAMENTO;

CREATE TABLE CLIENTE(
  IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM(M, F) NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE,
  SENHA VARCHAR(8)
);

INSERT INTO CLIENTE VALUES ('Ana Batista', 'F', 'ana.bastista@gmail.com', '016.434.987-65', '12345678');
INSERT INTO CLIENTE VALUES ('Gabriela Souza', 'F', 'gabisouza@gmail.com', '011.111.000-12', 'abcdef12');
INSERT INTO CLIENTE VALUES ('Pedro Andrade', 'M', 'pepe@gmail.com', '012.434.987-65', '12125678');
INSERT INTO CLIENTE VALUES ('Marcio Carlos', 'M', 'carlinhos@gmail.com', '017.434.987-65', '12165678');


CREATE TABLE PROFISSIONAL(
  IDPROFISSIONAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM(M, F) NOT NULL,
	CPF VARCHAR(15) UNIQUE,
  CELULAR CHAR(13) NOT NULL,
  CARGO VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50) UNIQUE,
  SENHA VARCHAR(8) NOT NULL
);

INSERT INTO PROFISSIONAL VALUES ('Jorge Amado', 'M', '015.324.123-63', '(61)981973462'), 'Enfermeiro', 'jorge.amado@gmail.com', 'abc12345') ;
INSERT INTO PROFISSIONAL VALUES ('Ana Paula', 'F', '010.324.123-63', '(61)981973772'), 'Endocrinologista', 'endocrino.ana@gmail.com', 'abcana12') ;
INSERT INTO PROFISSIONAL VALUES ('Caio Silva', 'M', '000.324.123-63', '(61)988873462'), 'Nutricionista', 'nutri.caio@gmail.com', 'caio2345') ;


CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM("COM", "RES", "CEL") NOT NULL,
	NUMERO VARCHAR(13) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO TELEFONE VALUES ('Com', '(61)981876545', 1);
INSERT INTO TELEFONE VALUES ('CEL', '(61)982876545', 1);
INSERT INTO TELEFONE VALUES ('Com', '(61)985876545', 2);
INSERT INTO TELEFONE VALUES ('Com', '(61)986876545', 3);
INSERT INTO TELEFONE VALUES ('Com', '(61)981877545', 4);


CREATE TABLE PROCEDIMENTO(
  IDPROCEDIMENTO INT PRIMARY KEY AUTO_INCREMENT,
  PROCEDIMENTO VARCHAR(30) NOT NULL,
  VALOR NUMERIC(10,2) NOT NULL,
  TEMPO VARCHAR(10) NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  FOREIGN KEY(ID_PROFISSIONAL) REFERENCES PROFISSIONAL(IDPROFISSIONAL)
);

INSERT INTO PROCEDIMENTO VALUES ('Tirar sangue', 150.50, '10min', 'Retirada de sangue no laboratorio');
INSERT INTO PROCEDIMENTO VALUES ('Consulta Nutricional', 400.00, '1h30min', 'Consulta em cosultorio');
INSERT INTO PROCEDIMENTO VALUES ('Retorno', 100.50, '1h', 'Retorno para avaliacao');




CREATE TABLE AGENDA(
  IDAGENDA INT PRIMARY KEY AUTO_INCREMENT,
  DATA DATE NOT NULL,
  HORA TIME NOT NULL,
  ID_CLIENTE INT NOT NULL,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE),
  ID_PROFISSIONAL INT NOT NULL,
  FOREIGN KEY(ID_PROFISSIONAL) REFERENCES PROFISSIONAL(IDPROFISSIONAL),
  ID_PROCEDIMENTO INT NOT NULL,
  FOREIGN KEY(ID_PROCEDIMENTO) REFERENCES PROCEDIMENTO(IDPROCEDIMENTO)
);

INSERT INTO AGENDA VALUES ('2019-07-08', '10:30:00', 1, 1, 1);
INSERT INTO AGENDA VALUES ('2019-07-09', '11:30:00', 2, 2, 3);
INSERT INTO AGENDA VALUES ('2019-07-10', '9:30:00', 3, 3, 2);
INSERT INTO AGENDA VALUES ('2019-07-11', '10:30:00', 4, 1, 3);


CREATE TABLE PROC_PROF(
  IDPROC_PROF INT PRIMARY KEY AUTO_INCREMENT,
  ID_PROFISSIONAL INT NOT NULL,
  FOREIGN KEY(ID_PROFISSIONAL) REFERENCES PROFISSIONAL(IDPROFISSIONAL),
  ID_PROCEDIMENTO INT NOT NULL,
  FOREIGN KEY(ID_PROCEDIMENTO) REFERENCES PROCEDIMENTO(IDPROCEDIMENTO)
)

INSERT INTO PROC_PROF VALUES (1, 1);
INSERT INTO PROC_PROF VALUES (1, 2);
INSERT INTO PROC_PROF VALUES (1, 3);
INSERT INTO PROC_PROF VALUES (2, 2);
INSERT INTO PROC_PROF VALUES (3, 3);
INSERT INTO PROC_PROF VALUES (3, 2);
