# Generated by Django 2.1.5 on 2019-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='one', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
